language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0

install:
  - cd example
  - pip install -r requirements.txt
  - pip install Django~=$DJANGO_VERSION

# command to run tests
script:
  coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test apps.test_security.tests --settings=settings.settings -v 2
