# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 13:15
from __future__ import unicode_literals

from django.db.models import F
from django.db import migrations, models
import django.utils.timezone


def set_estimated_time(apps, schema_editor):
    CeleryTaskLog = apps.get_model('security', 'CeleryTaskLog')
    CeleryTaskLog.objects.all().update(
        estimated_time_of_arrival=F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasklog',
            name='estimated_time_of_arrival',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='estimated time of arrival'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celerytasklog',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='retries'),
        ),
        migrations.AddField(
            model_name='celerytasklog',
            name='expires',
            field=models.DateTimeField(
                verbose_name='estimated time of arrival', null=True, blank=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_estimated_time),
    ]
